#STAR medicagoIndex.pbs
#!/bin/bash
#PBS -N medicago_Index
#PBS -l ncpus=8
#PBS -l mem=64gb
#PBS -m ae
#PBS -M abhat@bnl.gov

outputdir = "insert name of output directory here"

mkdir ${outputdir}

~/STAR-2.7.10a/bin/Linux_x86_64_static/STAR --runMode genomeGenerate \
--genomeDir ${outputdir} \
--genomeFastaFiles ~/Genomes/VTc07/Vtc07_genome_trd.fasta \
--sjdbGTFfile ~/Genomes/VTc07/Vtc07.436.gff \
--sjdbOverhang 100 \
--genomeSAindexNbases 10 \
--sjdbGTFfeatureExon CDS \
--runThreadN 8
