#STAR.pbs
#!/bin/bash
#PBS -N STAR_align
#PBS -l ncpus=8
#PBS -l mem=32gb
#PBS -m ae
#PBS -M mclear@bnl.gov

cd $PBS_O_WORKDIR

for i in $(ls *R1_paired.fq.gz | sed 's/R1_paired.fq.gz//')
do
STAR --runMode alignReads \
--readFilesCommand zcat \
--outSAMtype BAM Unsorted \
--genomeDir ~/Genomes_Indexed/STf07_Indexed \
--readFilesIn ${i}R1_paired.fq.gz  ${i}R2_paired.fq.gz \
--outReadsUnmapped Fastx \
--runThreadN 8 \
--quantMode GeneCounts \
-–sjdbGTFfile ~/Genomes/STf07/Stf07_491978.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentGene ID \
--outFileNamePrefix ${i}STf07 \
--alignIntronMax 3000
done
