# -*- coding: utf-8 -*-
"""
Created on Mon Oct 24 10:29:34 2022

@author: mclea
"""

import BioinformaticsLibrary as BL

BL.Zscore_from_GO_term_list(GO_term_file='Poplar_ion_clp_cellwall_GO_extracted_genes_L2FCtmmSplit.xlsx', 
                            count_file='Ptr_average_TMM.csv',
                            GO_annotation_file='Ptr_GO_annotation.tsv',
                            output_name='Poplar',
                            subset_list_1=['Leaf', 'Root'],
                            subset_list_2=['FeEx', 'FeLim', 'ZnEx', 'ZnLim'])

BL.goEnrich_DotPlot(adj_Pthresh=0.05, for_REVIGO=False, full_gProfiler='Sorg_full_go.csv', 
                     output_type='.pdf',
                     plot_width=15, plot_height=10,
                     dot_min_size=50,
                     dot_max_size=500,
                     sort_list=['GO:0016722 oxidoreductase activity, oxidizing metal ions',
                                'GO:0009834 plant-type secondary cell wall biogenesis',
                                'GO:0009664 plant-type cell wall organization',
                                'GO:0098869 cellular oxidant detoxification',
                                'GO:0034220 ion transmembrane transport',
                                'GO:0034755 iron ion transmembrane transport',
                                'GO:0005381 iron ion transmembrane transporter activity',
                                'GO:0005384 manganese ion transmembrane transporter activity',
                                'GO:0071421 manganese ion transmembrane transport',
                                'GO:0020037 heme binding',
                                'GO:0005506 iron ion binding',
                                'GO:0015995 chlorophyll biosynthetic process',
                                'GO:0016168 chlorophyll binding',
                                'GO:0015979 photosynthesis',
                                'GO:0046872 metal ion binding',
                                'GO:0005509 calcium ion binding',
                                'GO:0010207 photosystem II assembly',
                                'GO:0009658 chloroplast organization',
                                'GO:0005215 transporter activity',
                                'GO:0055085 transmembrane transport',
                                'GO:0030001 metal ion transport',
                                'GO:0003700 transcription factor activity, sequence-specific DNA binding',
                                'GO:0071577 zinc II ion transmembrane transport',
                                'GO:0005385 zinc ion transmembrane transporter activity'])

BL.goEnrich_DotPlot(adj_Pthresh=0.05, for_REVIGO=False, full_gProfiler='Pop_full_go.csv', 
                     output_type='.pdf',
                     plot_width=15, plot_height=15,
                     dot_min_size=50,
                     dot_max_size=500,
                     sort_list=['GO:0034220 ion transmembrane transport',
                                'GO:0042545 cell wall modification',
                                'GO:0016722 oxidoreductase activity, oxidizing metal ions',
                                'GO:0009664 plant-type cell wall organization',
                                'GO:0016998 cell wall macromolecule catabolic process',
                                'GO:0005381 iron ion transmembrane transporter activity',
                                'GO:0070588 calcium ion transmembrane transport',
                                'GO:0055085 transmembrane transport',
                                'GO:0051539 4 iron, 4 sulfur cluster binding',
                                'GO:0034755 iron ion transmembrane transport',
                                'GO:0005507 copper ion binding',
                                'GO:0071949 FAD binding',
                                'GO:0051537 2 iron, 2 sulfur cluster binding',
                                'GO:0051287 NAD binding',
                                'GO:0015979 photosynthesis',
                                'GO:0010206 photosystem II repair',
                                'GO:0005506 iron ion binding',
                                'GO:0008289 lipid binding',
                                'GO:0046916 cellular transition metal ion homeostasis',
                                'GO:0046914 transition metal ion binding',
                                'GO:0030001 metal ion transport',
                                'GO:0046872 metal ion binding',
                                'GO:0016168 chlorophyll binding',
                                'GO:0009768 photosynthesis, light harvesting in photosystem I',
                                'GO:0005509 calcium ion binding',
                                'GO:0071555 cell wall organization',
                                'GO:0042546 cell wall biogenesis',
                                'GO:0005385 zinc ion transmembrane transporter activity',
                                'GO:0071577 zinc II ion transmembrane transport',
                                'GO:0003700 transcription factor activity, sequence-specific DNA binding',
                                'GO:0050897 cobalt ion binding',
                                'GO:0020037 heme binding',
                                'GO:0098869 cellular oxidant detoxification',
                                'GO:0005215 transporter activity'])